# Generated by Django 4.1.7 on 2023-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('Gmail', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(default='', max_length=100)),
                ('usertype', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
