# Generated by Django 4.1.7 on 2023-04-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_myfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
